<?php
// php/crontab_generator.php

ini_set('display_errors', 'stderr');

// 1. config.json の読み込み
$config_file = __DIR__ . '/../config.json';
$config = ['db_path' => 'cron.db'];
if (file_exists($config_file)) {
    $loaded_config = json_decode(file_get_contents($config_file), true);
    if (is_array($loaded_config)) $config = array_merge($config, $loaded_config);
}

// 2. DBパス解決
$db_path_setting = $config['db_path'];
$db_file = (strpos($db_path_setting, '/') === 0) ? $db_path_setting : __DIR__ . '/../' . $db_path_setting;

// ★ 新規: ランナースクリプトのパス解決 ★
$runner_script = __DIR__ . '/cron_runner.php';

try {
    if (!file_exists($db_file)) throw new Exception("Database file not found at: " . $db_file);

    $db = new PDO("sqlite:$db_file");
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // 設定取得
    $cron_user = 'root'; 
    $check_table = $db->query("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='settings'")->fetchColumn();
    if ($check_table) {
        $stmt = $db->query("SELECT value FROM settings WHERE name = 'cron_user'");
        $val = $stmt->fetchColumn();
        if ($val) $cron_user = $val;
    }

    // 環境変数
    echo "# Generated by Web Cron Manager\n";
    echo "SHELL=/bin/bash\n"; 
    echo "PATH=/sbin:/bin:/usr/sbin:/usr/bin\n"; 

    $check_env = $db->query("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='environment_variables'")->fetchColumn();
    if ($check_env) {
        $env_vars = $db->query("SELECT name, value FROM environment_variables ORDER BY name ASC")->fetchAll(PDO::FETCH_ASSOC);
        if (!empty($env_vars)) {
            foreach ($env_vars as $env) {
                echo sprintf("%s=\"%s\"\n", $env['name'], $env['value']);
            }
        }
    }

    // ラッパー
    $wrappers = [];
    $check_wrapper = $db->query("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='wrappers'")->fetchColumn();
    if ($check_wrapper) {
        $wrappers = $db->query("SELECT name, value FROM wrappers")->fetchAll(PDO::FETCH_ASSOC);
    }

    // ジョブ出力
    // ジョブ出力
    $check_jobs = $db->query("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='jobs'")->fetchColumn();
    if ($check_jobs) {
        $jobs = $db->query("SELECT id, schedule, command FROM jobs ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);

        if (!empty($jobs)) {
            foreach ($jobs as $job) {
                $final_command = $job['command'];

                // ラッパー置換
                if (!empty($wrappers)) {
                    foreach ($wrappers as $wrap) {
                        $search = '${' . $wrap['name'] . '}';
                        $replace = $wrap['value'];
                        $final_command = str_replace($search, $replace, $final_command);
                    }
                }

                // ★ 修正: 先頭が # で始まる場合はコメントとみなし、runnerを通さない ★
                if (strpos(trim($final_command), '#') === 0) {
                    // シェル上でコメントとして扱われるよう、そのまま出力
                    // (例: * * * * * root # /path/to/command)
                    echo sprintf("%s %s %s\n", $job['schedule'], $cron_user, $final_command);
                } else {
                    // 通常実行: ランナースクリプト経由で実行
                    $wrapped_cmd = sprintf(
                        '/usr/bin/php %s %d %s',
                        escapeshellarg($runner_script),
                        $job['id'],
                        escapeshellarg($final_command)
                    );
                    echo sprintf("%s %s %s\n", $job['schedule'], $cron_user, $wrapped_cmd);
                }
            }
        } else {
            echo "# No jobs registered.\n";
        }
    }
} catch (Exception $e) {
    fwrite(STDERR, "Error in crontab_generator.php: " . $e->getMessage() . "\n");
    exit(1);
}
?>